### ISSUE TITLE
get_query_tables() is returning columns on WITH statements

### ISSUE THREAD

**Issue by remisalmon** [macbre/sql-metadata#128]
With sql-metadata==1.12.0,

```python
from sql_metadata import get_query_tables

q = "WITH t1 AS (SELECT * FROM t2), t3 (c1, c2) AS (SELECT c3, c4 FROM t4) SELECT * FROM t1, t3, t5;"

print(get_query_tables(q))
```

prints `['t2', 't3', 'c2', 'c4', 't4', 't1', 't5']` where `c2` and `c4` are columns.

This issue is not present with sql-metadata==1.11.0 and the code above prints `['t2', 't3', 't4', 't1', 't5']` as expected.

**Comment by collerek** [comment]
Note that `t1` and `t3` are not table names and in future versions they will not be included in `tables`.
(but they will be included in `with_names` so you can still fetch them if you need to).

If i got @macbre right `c1` and `c2` should not be included in columns either, as they are aliases for columns `c3` and `c4`.

**Comment by remisalmon** [comment]
> Note that `t1` and `t3` are not table names and in future versions they will not be included in `tables`.
> (but they will be included in `with_names` so you can still fetch them if you need to).
> 
> If i got @macbre right `c1` and `c2` should not be included in columns either, as they are aliases for columns `c3` and `c4`.

Agree with that.

Also, with the current master:

```python
from sql_metadata import Parser

q = "WITH t1 AS (SELECT * FROM t2), t3 (c1, c2) AS (SELECT c3, c4 FROM t4) SELECT * FROM t1, t3, t5;"

print(Parser(q).tables)
print(Parser(q).with_names)
```

prints `['t2', 't3', 'c1', 'c2', 't4', 't5']` and `['t1', ')']` (still an issue, just different than the one I posted above).
