### ISSUE TITLE
Not able to import parser however get_query_tables() is working

### ISSUE THREAD

**Issue by anurag-shekhar** [macbre/sql-metadata#132]
<img width="1342" alt="Screenshot 2021-05-10 at 1 15 23 PM" src="https://user-images.githubusercontent.com/83714201/117623760-d2351300-b191-11eb-92dc-07d314416bd7.png">

from sql_metadata import Parser

**Comment by macbre** [comment]
Which version of `sql_metadata` have you installed in your Jupyter? `Parser` is a new thing, not yet present in PyPI package. You have to use the version fetched directly via git for the time being. Sorry for the confusion.

**Comment by macbre** [comment]
@anurag-shekhar - please refer to https://github.com/macbre/sql-metadata#migrating-from-sql_metadata-1x (added as a part of #137)

**Comment by macbre** [comment]
@anurag-shekhar - please use the latest `sql_metadata` PyPi package that has just been published - https://pypi.python.org/pypi/sql_metadata

**Comment by anurag-shekhar** [comment]
Thanks for the update @macbre
