### ISSUE TITLE
complex query can't get all columns

### ISSUE THREAD

**Issue by annisun2020** [macbre/sql-metadata#144]
query:
`select targetingtype,
       sellerid,
       sguid,
       'd01' as datetype,
       adgroupname,
       targeting,
       customersearchterm,
       'product_search_term' as type,
       sum(impressions) as impr,
       sum(clicks) as clicks,
       sum(seventotalunits) as sold,
       sum(sevenadvertisedskuunits) as advertisedskuunits,
       sum(sevenotherskuunits) as otherskuunits,
       sum(sevendaytotalsales) as totalsales,
       round(sum(spend), 4) as spend,
       if(sum(impressions) > 0, round(sum(clicks)/sum(impressions), 4), 0) as ctr,
       if(sum(clicks) > 0, round(sum(seventotalunits)/sum(clicks), 4), 0) as cr,
       if(sum(clicks) > 0, round(sum(spend)/sum(clicks), 2), 0) as cpc
from amazon_pl.search_term_report_impala
where reportday >= to_date('2021-05-16 00:00:00.0') and reportday <= to_date('2021-05-16 00:00:00.0') and targetingtype in ('auto','manual')
and sguid is not null and sguid != ''
group by targetingtype,sellerid,sguid,adgroupname,targeting,customersearchterm 
order by impr desc`

I get the defect columns list:

['targetingtype', 'sellerid', 'sguid', 'adgroupname', 'targeting', 'customersearchterm', 'reportday', 'impr']

impressions,clicks etc. columns is missing

**Comment by macbre** [comment]
It seems that there's a problem with nested parenthesis support in `if` statements:

```
if(sum(impressions) > 0, round(sum(clicks)/sum(impressions), 4), 0) as ctr
```

**Comment by collerek** [comment]
There are 2 problems.
1. column_alias is a keyword (`type`), for this quoting (or change of name) will help
2. columns aliases for `clicks` and `spend` are same as column names (but since they are in aliases names they are skipped) -> this one we need to fix
