### ISSUE TITLE
The tables property is still having difficulties finding the tables in a CTAS

### ISSUE THREAD

**Issue by tipanverella** [macbre/sql-metadata#155]
I created the following test:

```
def test_create_table_as_select_with_joins_with():
    qry = """
        CREATE table xyz as 
        with sub as (select it_id from internal_table)
        SELECT *
        from table_a
        join table_b on (table_a.name = table_b.name)
        left join table_c on (table_a.age = table_c.age)
        left join sub on (table.it_id = sub.it_id)
        order by table_a.name, table_a.age
        """
    parser = Parser(qry)
    assert set(parser.tables) == set(["xyz", "table_a", "table_b", "table_c", "internal_table"])
```

And the code is not able to pass it as is.  It seems that it struggles with `with` created subqueries.

**Comment by collerek** [comment]
I've never seen create table with with clause in practice. It's Oracle that you are using our is it allowed also in different backends?

**Comment by tipanverella** [comment]
I am using [AWS Athena](https://aws.amazon.com/athena/), which is essentially [Presto](https://prestodb.io/)

**Comment by tipanverella** [comment]
Please let me know if I can help fixing this problem.

**Comment by collerek** [comment]
PR with a fix was just opened.

Note that you do not have to convert to a set -> we return already unique set of values.
The reason it's a list is to preserve the order of occurrence in the query which set does not provide, but in reality it's a custom subclass of a list that keeps only unique entries in order of first occurrence.

BTW I didn't see you in stargazers of sql-metadata, you know we fix only issues from people that help us to promote our library 😛 🤣

**Comment by macbre** [comment]
> BTW I didn't see you in stargazers of sql-metadata, you know we fix only issues from people that help us to promote our library 😛 🤣

We should state that in our `CONTRIBUTING.md` 😉
