### ISSUE TITLE
Regression 1.12 -> 2.x with CREATE TABLE AS (...) requests

### ISSUE THREAD

**Issue by YoannQDQ** [macbre/sql-metadata#160]
I use sql-metadata (great module btw) to extract tables used by `CREATE TABLE` requests. I recently upgraded sql-metadata to 2.X, and broke my entire code :'(

Behavior with sql-metadata 1.12 (Good, at least for my use case)
```
>>> from sql_metadata import get_query_tables
>>> sql = CREATE TABLE records AS (SELECT t.id, t.name, e.name as energy FROM t JOIN e ON t.e_id = e.id)
>>> get_query_tables(sql)
['records', 't', 'e']
```
Behavior with sql-metadata 2.X (Less good...)
```
>>> from sql_metadata.compat import get_query_tables
>>> from sql_metadata import Parser
>>> sql = CREATE TABLE records AS (SELECT t.id, t.name, e.name as energy FROM t JOIN e ON t.e_id = e.id)
>>> get_query_tables(sql)
['records']
>>> Parser(sql).tables
['records']
```

**Comment by collerek** [comment]
Hi, this is a bug related to oversimplified handling of parentheses (reported in #154) and fixed in #157 (waiting for review).

As a quick and dirty workaround you can:
1. Pip install from #157 branch
2.  Remove the parenthesis around select subquery

Otherwise we need to wait for @macbre approval.

**Comment by collerek** [comment]
@macbre this one also should be fixed by #157 (sample query provided was tested).

I would expect that gentlemen would be thankful for a release as you cannot pin the version from GitHub (although I think you can install given commit?).

What is your view on shortening change to release period and release more but smaller versions?

You know, it's more `<buzzword>agile</buzzword>`🤣

**Comment by macbre** [comment]
I can't disagree with the Agile buzzword 😆 Will prepare the v2.2 release shortly.

**Comment by macbre** [comment]
https://github.com/macbre/sql-metadata/releases/tag/v2.2.0 published.

@YoannQDQ - hope it will work for you now.

**Comment by YoannQDQ** [comment]
Yes it does, thanks!
