### ISSUE TITLE
get_query_tables() breaks on `INSERT INTO ... SELECT`

### ISSUE THREAD

**Issue by dargueta** [macbre/sql-metadata#18]
Inserting data into a table via a `SELECT` query seems to break `get_query_tables()`:

Minimal example:

For this query...

```sql
INSERT INTO foo
SELECT
  *
FROM bar
```

...running `get_query_tables()` returns this:

```py
['foo', 'SELECT', 'bar']
```

The expected output is `['bar']` or maybe `['foo', 'bar']`.

Environment:

Python: 3.7.0
OS: macOS High Sierra 10.13.6

Packages installed:
```
sql-metadata==1.1.2
sqlparse==0.2.4
```

**Comment by macbre** [comment]
@dargueta, thanks for your bug report! It has been fixed by #21. I'll publish a new version of `sql-metadata` shortly.

Out of curiosity, what do you use `sqll-metadata` package for?

**Comment by macbre** [comment]
See https://github.com/macbre/sql-metadata/releases/tag/v1.2

**Comment by dargueta** [comment]
Thanks a lot!

> Out of curiosity, what do you use `sqll-metadata` package for?

I'm using it at work for automatically detecting dependencies between scripts generating tables in our ETL. Right now we do it manually, prefix files with numbers, and then run them in series. By detecting dependencies automatically, we can run unrelated files in parallel and get a significant performance boost.
