### ISSUE TITLE
AttributeError: 'Parser' object has no attribute 'with_queries'

### ISSUE THREAD

**Issue by Belkachait08** [macbre/sql-metadata#181]
In the example :

`from sql_metadata import Parser`

`parser = Parser(`
`    """`
`WITH`
`    database1.tableFromWith AS (SELECT aa.* FROM table3 as aa `
`                                left join table4 on aa.col1=table4.col2),`
`    test as (SELECT * from table3)`
`SELECT`
`  "xxxxx"`
`FROM`
`  database1.tableFromWith alias`
`LEFT JOIN database2.table2 ON ("tt"."ttt"."fff" = "xx"."xxx")`
`"""`
`)`
`parser.with_queries`

The `parser.with_queries` line gives out the following output : 

 AttributeError: 'Parser' object has no attribute 'with_queries'

**Comment by collerek** [comment]
I don't know of this is related to the error but you cannot have database prefixed column in on clause, so `tt.ttt.fff` identifier is not a valid SQL (at least in backends that I know).

Can you check if the error persist when you change it to i.e. `ttt.fff`

**Comment by Belkachait08** [comment]
I simplified the query
`from sql_metadata import Parser`
`parser = Parser(`
 `   """`
`with test as (SELECT  xxx FROM db)`
`    SELECT * from test`
`"""`
`)`

`# get names/ aliases of with statements`
`parser.with_queries`
`# ["database1.tableFromWith", "test"]`

I still have the same error:
AttributeError: 'Parser' object has no attribute 'with_queries'

**Comment by macbre** [comment]
How did you install sql-metadata? Via pip or git?

**Comment by collerek** [comment]
@macbre we didn't release resolving with queries yet? 😱

**Comment by Belkachait08** [comment]
> How did you install sql-metadata? Via pip or git?

I used pip

**Comment by macbre** [comment]
@collerek - it seems like it - https://github.com/macbre/sql-metadata/compare/v2.2.1...master.diff

@Belkachait08 - we'll publish the most up to date version of sql-metadata soon.

**Comment by macbre** [comment]
@collerek / @Belkachait08 - [v2.2.2 is there](https://github.com/macbre/sql-metadata/releases/tag/v2.2.2) 🚀 

https://pypi.org/project/sql-metadata/ has the latest version now.

**Comment by Belkachait08** [comment]
Perfect.
Thank you !
