### ISSUE TITLE
Case sensitivity columns and tables

### ISSUE THREAD

**Issue by ReinierKoops** [macbre/sql-metadata#183]
Hi, thank you for making this awesome repository.

I would like to ask about the following; I have found that the implementation of queries is case sensitive for the following use case:

`from sql_metadata import Parser`

`sql_3 = "SELECT name FROM singer WHERE birth_Year = 1948 UNION ALL SELECT name FROM Singer WHERE birth_year = 1949"`

`parsed_sql = Parser(sql_3)`
`print(parsed_sql.columns, parsed_sql.tables)`

output: ['name', 'birth_Year', 'birth_year'] ['singer', 'Singer'] 

`sql_4 = "SELECT name FROM singer WHERE birth_year = 1948 OR birth_year = 1949"`

`parsed_sql = Parser(sql_4)`
`print(parsed_sql.columns, parsed_sql.tables)` 

output: ['name', 'birth_year'] ['singer']

Not sure if that is intended or not. If not, hope this helps.

**Comment by collerek** [comment]
Yes, some backends column names are case sensitive (i.e. quoted postgres column names), so this behavior is expected.
If you don't care about case sensitivity you can pass the whole query string with `lower()` applied to avoid such cases.
