### ISSUE TITLE
Wrong output for parsing tables list if query has aggregation

### ISSUE THREAD

**Issue by saranib** [macbre/sql-metadata#186]
I am getting some extra invalid values for getting the list of tables for below example:

>>>from sql_metadata import Parser
>>> qry="""
SELECT 
       tc.col2
          , max(tc.col3) col3_mx
           , trunc(max(tc.col4)) col4_mx
        , extract (week from (max(tc.col5))) col5_week
            , sum(NVL(tc.amt,0)) tot_amt
    FROM 
       my_sc.tab1 tc
   WHERE 
      tc.col1 = 'AAA'
   group by 
         tc.col2
 """
>>> parser = Parser(qry)
>>> parser.tables
['max', 'tc.col5', 'sum', 'NVL', 'tc.amt', 'my_sc.tab1']
>>> 

It should have returned only my_sc.tab1 for the tables list

**Comment by collerek** [comment]
That's caused by `from` in `extract (week from (max(tc.col5)))` part not the aggregation.
We need to work around this, cause as of now we treat `from` as an indicator of tables.

**Comment by saranib** [comment]
I have pulled from branch multi_from_aliases, but it still returns the extra values for my query

**Comment by collerek** [comment]
If you literally pulled from the branch you just created a local copy, you need to pip install from that branch in your project: https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch
