### ISSUE TITLE
Query including Distinct not working

### ISSUE THREAD

**Issue by Hariomsingh2007** [macbre/sql-metadata#188]
```
sql_new="SELECT DISTINCT customer_id FROM table"

parsed = Parser(sql_new)

print("columns-->", parsed.columns)
```
Result:
`columns--> []`

The above query is not working .

**Comment by ReinierKoops** [comment]
I have just found about this problem as well and tested branch #187 which fixes the issue 😄

**Comment by macbre** [comment]
Thanks, @ReinierKoops !
