### ISSUE TITLE
Installed sql-metadata (Python1.8.0) but code shows syntax error - Python 2.7

### ISSUE THREAD

**Issue by ShivaniMR** [macbre/sql-metadata#196]
@macbre ,  Can you please help on why I am encountering this error? 
--------------------------------------------------------Error

 File "/root_file_path/python_programs/nameofvirtualenvironment/lib/python2.7/site-packages/sql_metadata.py", line 19
    def preprocess_query(query: str) -> str:
                              ^
SyntaxError: invalid syntax

-------------------------------------------------------
#Python_script content
from sql_metadata import Parser
Parser("SELECT a.* FROM product_a.users AS a JOIN product_b.users AS b ON a.ip_address = b.ip_address").tables

**Comment by collerek** [comment]
This package requires python >=3.6.2.
Your syntax error refers to type hints that python 2.7 does not support.

**Comment by ShivaniMR** [comment]
oh okay, got it, Thank you Collerek. Will try that

**Comment by ShivaniMR** [comment]
Anyway, I can use the sql_metadata.py found in this location from the .whl file and not parser.py contents right?
https://pypi.org/project/sql-metadata/#modal-close

**Comment by collerek** [comment]
.whl is just a built package (so you don't have to build from the source).
You still need to install it with pip to use it.

You can read more i.e. here https://realpython.com/python-wheels/
