### ISSUE TITLE
Issue with Parser().columns_dict

### ISSUE THREAD

**Issue by kushanthap** [macbre/sql-metadata#198]
Hi,

I am having issues using .columns_dict with certain queries.

See below example with a simplified query. Nothing get returned and it breaks the kernel (unresponsive).

`Parser('''select a from tb1 where b in (select distinct b from tb2)''').columns_dict`

Below examples seem to works fine. So, having 'distinct' or having the same column name in sub query, individually is not causing this issue.
`Parser('''select a from tb1 where b in (select b from tb2)''').columns_dict`
`Parser('''select a from tb1 where b in (select distinct c from tb2)''').columns_dict`

**Comment by collerek** [comment]
Can you provide the expected and actual output for that query?

**Comment by kushanthap** [comment]
Query in question:
`Parser('''select a from tb1 where b in (select distinct b from tb2)''').columns_dict`

Expected Output:
`{'select': ['a', 'b'], 'where': ['b']}`

Actual Output: None. Make the kernal go unresponsive.

**Comment by kushanthap** [comment]
Another example ( a rare scenario I must say)

Query:
`Parser('''select a as b, b as a from tb''').columns_dict`

Expected output:
`{'select': ['a', 'b']}`

Actual output: runs indefinitely, no output


All above examples `Parser().columns` seems t run okay.
