### ISSUE TITLE
Alias and column names from subquery are case sensitive when used as conditions in outer query

### ISSUE THREAD

**Issue by christopherpickering** [macbre/sql-metadata#202]
It seem like case must match on alias/column names from subquery when they are used as a condition in the outer query, *only* if the subquery alias is used in the condition.

for example, this works:
```sql
select tEsT
from (select a as TeSt from nowhere) as t
where tEsT = 'asdf'
```

but this fails:
```sql
select tEsT
from (select a as TeSt from nowhere) as t
where t.tEsT = 'asdf'
```
with an error
```error
ValueError: 'tEsT' is not in list
```

I think it can be fixed by ignoring case when checking column alias.

In Parser.py, `_resolve_nested_query, we can change
```py
if column_name in subparser.columns_aliases_names:
```
to
```py
if column_name.lower() in [x.lower() for x in subparser.columns_aliases_names]:
```
or 
```py
if any(filter(lambda x: x.lower() == column_name.lower(),subparser.columns_aliases_names)):
```
... not sure of a nicer way to say it.

 I'll put a pull request w/  a test.

**Comment by collerek** [comment]
Yes, the sql-metadata is case sensitive as some backends like postgres with quoted names are case sensitive. If you don't need this put your query in lower or upper before parsing.

**Comment by christopherpickering** [comment]
Oh shucks, Thats valid I guess. Who's case sensitive? I can remove what I added in the PR for case.
