### ISSUE TITLE
Fully qualified columns are not matched

### ISSUE THREAD

**Issue by christopherpickering** [macbre/sql-metadata#209]
A sql that parses:
```sql
select a.col, b.col from dbo.a
, db_two.dbo.b
where a.col = b.col
```

but when the columns are fully qualified (schema.table.column) outside the `FROM` clause, there is no match found.

These fail, but are valid sql:

full qualified in the condition
```sql
select a.col, b.col from dbo.a
, db_two.dbo.b
where dbo.a.col = b.col
```

fully qualified in the select
```sql
select dbo.a.col, b.col from dbo.a
, db_two.dbo.b
where a.col = b.col
```

also with database name
```sql
select a.col, db_two.dbo.b.col from dbo.a
, db_two.dbo.b
where a.col = db_two.dbo.b.col
```

**Comment by collerek** [comment]
As far as I remember you cannot have fully qualified names outside of from clause in most of the backend (all I know quite well). Which backend are you using?

**Comment by christopherpickering** [comment]
Sql server :/ it parses them as valid.

**Comment by collerek** [comment]
Ok i haven't used this one in a while will check that. (We used to have this but we checked some references on most popular backends and they seemed to point out that you can have only table names in that format, seems they were wrong). Thanks for pointing that out! 😊

**Comment by christopherpickering** [comment]
Thank you! I appreciate the tool!
