### ISSUE TITLE
Support 'CREATE TABLE IF NOT EXISTS'

### ISSUE THREAD

**Issue by HannesHil** [macbre/sql-metadata#213]
When using commands like 
```
CREATE TABLE IF NOT EXISTS analytics_table (
	version int4 NULL
)
```
the parser gets confused concerning the table name and probably other variables.

**Comment by collerek** [comment]
Support for if not exists was added in #224.

But note that you are using the SQL keyword `version` as a column name which is not recommended (in some backends can have weird behavior). 

If you really want to keep that name you need to quote it:
```sql
CREATE TABLE IF NOT EXISTS analytics_table (
	`version` int4 NULL
)
```
