### ISSUE TITLE
Parser.tables/ compat.get_query_tables(sql) can not recognize the table name contains space

### ISSUE THREAD

**Issue by sumi2017** [macbre/sql-metadata#214]
Parser sql query:
SELECT a.Name
FROM Abcde fghijk lmn AS a
WHERE .... (condition)

it recognizes the table as "Abced", not "Abcde fghijk lmn "

I thought it should be related to the split the String by space.

**Comment by collerek** [comment]
Cause that's an invalid sql, you cannot have whitespaces in qualifiers.

To make it work you need to quote the whole thing (note the backticks - ` around the table name)

```
Parser sql query:
SELECT a.Name
FROM `Abcde fghijk lmn` AS a
WHERE .... (condition)
```

**Comment by sumi2017** [comment]
Ok, thank you!
