### ISSUE TITLE
Add table_dict functionality.

### ISSUE THREAD

**Issue by ajith1108** [macbre/sql-metadata#215]
Hi, 
 The dictionary mapping is available only for the columns.If the dictionary mapping is available for tables also means it would be great .For example mapping the columns to their respective tables.

Expecting something like this
{'TABLE' : [COL1,COL2]8}

**Comment by collerek** [comment]
We would love to, but without the inspection if the actual databases that is often impossible if you do not prefix the columns with the tables.

I.e: `select col1, col2 from table1, table2`. Without the database there is no way from which table which column is coming from. And that is a valid query. That is the case in many queries.

**Comment by ajith1108** [comment]
Thanks..If you know any work around please share it.
