### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by ajith1108** [macbre/sql-metadata#221]
Hi,
 I'm trying parse a huge query which contains multiple subqueries and union all statements along with many case conditions.
But I'm getting pop from empty list error. I've pasted the complete error message below. Let me know the reason for this error.

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-45-cd845012da3b> in <module>
----> 1 Parser(data).tables

~\Anaconda3\lib\site-packages\sql_metadata\parser.py in tables(self)
    420             return self._tables
    421         tables = UniqueList()
--> 422         with_names = self.with_names
    423 
    424         for token in self.tokens:

~\Anaconda3\lib\site-packages\sql_metadata\parser.py in with_names(self)
    546             return self._with_names
    547         with_names = UniqueList()
--> 548         for token in self.tokens:
    549             if token.previous_token.normalized == "WITH":
    550                 self._is_in_with_block = True

~\Anaconda3\lib\site-packages\sql_metadata\parser.py in tokens(self)
    149                 self._determine_opening_parenthesis_type(token=token)
    150             elif token.is_right_parenthesis:
--> 151                 self._determine_closing_parenthesis_type(token=token)
    152 
    153             if tok.is_keyword and "".join(tok.normalized.split()) in RELEVANT_KEYWORDS:

~\Anaconda3\lib\site-packages\sql_metadata\parser.py in _determine_closing_parenthesis_type(self, token)
    898         Determines the type of right parenthesis in query
    899         """
--> 900         last_open_parenthesis = self._open_parentheses.pop(-1)
    901         if last_open_parenthesis.is_subquery_start:
    902             token.is_subquery_end = True

IndexError: pop from empty list

**Comment by collerek** [comment]
Hi, it seems like parser encountered closing parenthesis without opening one. Did you run the query to check if it's working? If yes we would need the query to debug it further.

**Comment by ajith1108** [comment]
Found a way around.
