### ISSUE TITLE
SQL query parser not returning proper column aliases

### ISSUE THREAD

**Issue by Vigneshg98** [macbre/sql-metadata#226]
When using Parser for the below query, the Parser returns improper data considering CAST type as an alias name.

**Query:**
```
  SELECT
    t_alias.id as UniqueId,
    CAST(date_format(t_alias.date, 'yyyyMMdd') as INT) as datekey,
    CAST(concat( \
     '1', \
      case when LENGTH(hour(t_alias.starttime)) > 1 \
          then hour(t_alias.starttime) \
          else concat('0', hour(t_alias.starttime)) end \
      ,\
      case when LENGTH(minute(t_alias.starttime)) > 1 \
          then minute(t_alias.starttime) \
          else concat('0', minute(t_alias.starttime)) end \
      ) as INT) \
    as starttimekey
  FROM testdb.test_table t_alias
  ```
```
query = <above query>
parser_object = Parser(query)
print(parser_object.columns_aliases)
```

**Returned Parser Output:**
```
{
    "UniqueId": "testdb.test_table.id", 
    "INT": "testdb.test_table.date", 
    "datekey": ["testdb.test_table.date", "INT"], 
    "starttimekey": ["testdb.test_table.starttime", "t_alias.starttime", "INT"]
}
```

**Expected Output:**
```
{
  "UniqueId": "testdb.test_table.id",
  "datekey": "testdb.date",
  "starttimekey": "testdb.starttime"
}
```

**Comment by collerek** [comment]
This one is already fixed on master but not released yet.

As a workaround, you can pip install from GitHub.

**Comment by Vigneshg98** [comment]
Thanks @collerek 
I tried installing using the below command. But still, the same result is returned from the Parser.

`pip install git+https://github.com/macbre/sql-metadata.git@check_aliases_with_cast`

![image](https://user-images.githubusercontent.com/30794187/133030478-92913454-59f7-4a26-b2ff-dd8490dfa9ed.png)

![image](https://user-images.githubusercontent.com/30794187/133030556-daa0a0cd-2489-460d-b470-31d862660585.png)

Could you please let me know if I am missing out anything?
