### ISSUE TITLE
Getting "Not supported query type" for a SELECT query

### ISSUE THREAD

**Issue by ajith1108** [macbre/sql-metadata#227]
I was trying to extract the columns names form a SAS query but its throwing an error as not supported query type even though the query falls under the supported format.

The  first part of query is below, If needed I can send the complete query.

SELECT
  DISTINCT party.CHN_PARTY_PD_ID,
  fida.BIRTH_YEAR_MONTH_DT,
  w.RESOURCE_LEVEL_11_TXT,
  q2.*
FROM
  (
    SELECT
      q1.CHN_PARTY_SK,
      q1.PERIOD_END_DT,
      CASE WHEN q1.PRODUCT_SERVICE_OFFERED_CD = 'VRA' THEN q1.PERIOD_END_DT ELSE halalip.PIT_VALUATION_DT END AS PIT_VALUATION_DT,
      CASE WHEN q1.PRODUCT_SERVICE_OFFERED_CD = 'VRA' THEN q1.PERIOD_END_DT ELSE CASE WHEN min(halalip.PIT_VALUATION_DT) OVER (PARTITION BY q1.ARRANGEMENT_ID, q1.PERIOD_END_DT) <= q1.PERIOD_END_DT THEN max(
        CASE WHEN halalip.PIT_VALUATION_DT <= q1.PERIOD_END_DT THEN halalip.PIT_VALUATION_DT END
      ) OVER (PARTITION BY q1.ARRANGEMENT_ID, q1.PERIOD_END_DT) ELSE min(halalip.PIT_VALUATION_DT) OVER (PARTITION BY q1.ARRANGEMENT_ID, q1.PERIOD_END_DT) END END AS MAXPIT,
      CASE WHEN q1.PRODUCT_SERVICE_OFFERED_CD = 'VRA' THEN q1.ARRANGEMENT_ID ELSE halalip.CONTRACT_ID END AS CONTRACT_ID,
      q1.ARRANGEMENT_ID,
      q1.RULE_TYPE_CD,
      q1.PERIOD_TYPE_CD,
      q1.MAJOR_BUSINESS_UNIT_CD,
      q1.EIA_PROD_SVC_LINE_OF_BUS_CD,
      q1.PRODUCT_SERVICE_OFFERED_CD,
      q1.EIA_PROD_SVC_QUALIFIER_CD,
      q1.PROD_SERVICE_DESCRIPTION_TXT,
      q1.AGR_EFF_DT,
      q1.AGR_STA_DC,
      q1.EFF_DT,
      q1.PRODUCT_ACQUIRED_DT,
      q1.GENDER_CD AS Gender,
      q1.MARITAL_STATUS_CD AS MaritalStatus,
      q1.MKT_PERF_CTGY_GROUP_DC AS Membership,
      q1.AGE_BAND_NM AS AgeBand,
      q1.AQUISTION_CHANNEL_DC AS Channel,
      q1.ACTL_RES_LOC_DC,
      CASE WHEN substr(ACTL_RES_LOC_CD, 1, 1) = '0'
      AND substr(ACTL_RES_LOC_CD, 2, 1) IN ('0', '1', '2', '3', '4', '5')
      AND ACTL_RES_LOC_CD <> '000' THEN ACTL_RES_LOC_DC --basically anything under 059 is a US State/DC except for 000
      WHEN ACTL_RES_LOC_CD IN ('711', '703', '706', '708', '312', '310', '099') THEN 'Territory' -- American Samoa, Guam, N Mariana Islands, Midway Islands, USVI, Puerto Rico, United States
      WHEN ACTL_RES_LOC_DC = 'UNKNOWN' THEN 'Unknown' ELSE 'Outside U.S.' END AS STATE,
      CASE WHEN q1.PRODUCT_SERVICE_OFFERED_CD = 'VRA' --Variable Annuity IRAs don't show up in HAL or ALIP so we have to use the GLN table/fake everything for them
      THEN CASE WHEN EIA_PROD_SVC_QUALIFIER_CD = 'NQA' THEN 'NQA' ELSE 'IRA' END ELSE halalip.TAX_QUALIFICATION_AC END AS TAX_QUALIFICATION_AC,
      CASE WHEN q1.PRODUCT_SERVICE_OFFERED_CD = 'VRA' --Variable Annuity IRAs don't show up in HAL or ALIP so we have to use the GLN table/fake everything for them
      THEN NULL ELSE halalip.FUNDING_SOURCE END AS FUNDING_SOURCE,
      CASE WHEN q1.PRODUCT_SERVICE_OFFERED_CD = 'VRA' --Variable Annuity IRAs don't show up in HAL or ALIP so we have to use the GLN table/fake everything for them
      THEN q1.PRODUCT_ACQUIRED_DT ELSE halalip.ISSUE_DT END AS CONTRACT_ISSUE_DT,
      CASE WHEN q1.PRODUCT_SERVICE_OFFERED_CD = 'VRA' --Variable Annuity IRAs don't show up in HAL or ALIP so we have to use the GLN table/fake everything for them
      THEN q1.EFF_DT ELSE halalip.CONTRACT_EFFECTIVE_DT END AS Prod_Eff_DT,
      halalip.WORKER_PARTY_ID AS WORKER_PARTY_ID,
      halalip.CONTRACT_TOTAL_FUND_VALUE_AMT AS FACE_AMT,
      halalip.CONTRACT_TOTAL_FUND_VALUE_AMT AS maxface,
      CASE WHEN q1.RULE_TYPE_CD = 'C'
      OR PERIOD_TYPE_CD = 'M' THEN q1.PERIOD_END_DT ELSE min(q1.PERIOD_END_DT) OVER (PARTITION BY q1.ARRANGEMENT_ID, q1.RULE_TYPE_CD) END AS minnewlost
    FROM
      (
        (
          SELECT
            min(CHN_PARTY_SK) OVER (
              PARTITION BY PERIOD_END_DT,
              ARRANGEMENT_ID,
              PERIOD_TYPE_CD
            ) AS minUSAA_PARTY_SK,
            CHN_PARTY_SK,
            PERIOD_END_DT,
            ARRANGEMENT_ID,
            RULE_TYPE_CD,
            PERIOD_TYPE_CD,
            MAJOR_BUSINESS_UNIT_CD,
            EIA_PROD_SVC_LINE_OF_BUS_CD,
            PRODUCT_SERVICE_OFFERED_CD,
            EIA_PROD_SVC_QUALIFIER_CD,
            PROD_SERVICE_DESCRIPTION_TXT,
            AGR_EFF_DT,
            AGR_STA_DC,
            EFF_DT,
            PRODUCT_ACQUIRED_DT,
            GENDER_CD,
            MARITAL_STATUS_CD,
            MKT_PERF_CTGY_GROUP_DC,
            AGE_BAND_NM,
            AQUISTION_CHANNEL_DC,
            ACTL_RES_LOC_CD,
            ACTL_RES_LOC_DC,
            0 AS LOST_LAST_WEEK,
            0 AS NEW_LAST_WEEK,
            '2019-01-01' AS LAST_DOM
          FROM
            STDFMDB.MIN.M_NCP_FC_LIFE_NEW_LOST_PRD n
          WHERE
            EIA_PROD_SVC_LINE_OF_BUS_CD = 'ANN'
            AND n.PERIOD_END_DT >= '2019-01-01'
        )
        UNION ALL
          (
            SELECT
              *
            FROM
              (
                SELECT
                  min(CHN_PARTY_SK) OVER (
                    PARTITION BY PERIOD_END_DT,
                    ARRANGEMENT_ID,
                    PERIOD_TYPE_CD
                  ) AS minUSAA_PARTY_SK,
                  CHN_PARTY_SK,
                  PERIOD_END_DT,
                  ARRANGEMENT_ID,
                  RULE_TYPE_CD,
                  'W' AS PERIOD_TYPE_CD,
                  MAJOR_BUSINESS_UNIT_CD,
                  EIA_PROD_SVC_LINE_OF_BUS_CD,
                  PRODUCT_SERVICE_OFFERED_CD,
                  EIA_PROD_SVC_QUALIFIER_CD,
                  PROD_SERVICE_DESCRIPTION_TXT,
                  AGR_EFF_DT,
                  AGR_STA_DC,
                  EFF_DT,
                  PRODUCT_ACQUIRED_DT,
                  GENDER_CD,
                  MARITAL_STATUS_CD,
                  MKT_PERF_CTGY_GROUP_DC,
                  AGE_BAND_NM,
                  AQUISTION_CHANNEL_DC,
                  ACTL_RES_LOC_CD,
                  ACTL_RES_LOC_DC,
                  sum(CASE WHEN RULE_TYPE_CD = 'L' THEN 1 ELSE 0 END) OVER (
                    PARTITION BY ARRANGEMENT_ID,
                    month(PERIOD_END_DT)
                  ) as LOST_LAST_WEEK,
                  sum(CASE WHEN RULE_TYPE_CD = 'N' THEN 1 ELSE 0 END) OVER (
                    PARTITION BY ARRANGEMENT_ID,
                    month(PERIOD_END_DT)
                  ) as NEW_LAST_WEEK,
                  max(PERIOD_END_DT) OVER (PARTITION BY month(PERIOD_END_DT)) AS LAST_DOM
                FROM
                  STDFMDB.MIN.M_NCP_FC_LIFE_NEW_LOST_PRD n
                WHERE
                  EIA_PROD_SVC_LINE_OF_BUS_CD = 'ANN'
                  AND n.PERIOD_END_DT >= '2019-01-01'
              ) clw
            WHERE
              RULE_TYPE_CD <> 'C'
              AND LAST_DOM = PERIOD_END_DT
              AND (
                LOST_LAST_WEEK = 1
                OR NEW_LAST_WEEK = 1
              )
          )
      ) q1
      LEFT JOIN (
        (
          --REGION HAL Section
          SELECT
            DISTINCT i.AGREEMENT_CONTRACT_ID_NR AS ARRANGEMENT_ID,
            AGREEMENT_CONTRACT_ID_NR AS CONTRACT_ID,
            e.ACT_PRODUCT_ARRANGEMENT_SK,
            i.CHN_PARTY_SK,
            e.CONTRACT_ISSUE_DT AS ISSUE_DT,
            e.CONTRACT_EFFECTIVE_DT,
            app.REQUESTOR_USER_ID AS WORKER_PARTY_ID,
            i.TAX_QUALIFICATION_AC,
            e.PIT_VALUATION_DT,
            CASE WHEN laair.INSURANCE_CONTRACT_REPL_AC = 'C' THEN 'CONVERSION' WHEN laair.INSURANCE_CONTRACT_REPL_AC IN ('E', 'R')
            AND laair.INSURED_W_USAA_GROUP_AC = 'Y' THEN 'INTERNAL_EXCHG' WHEN laair.INSURANCE_CONTRACT_REPL_AC IN ('N', 'R')
            AND laair.INSURED_W_USAA_GROUP_AC = 'N' THEN 'EXTERNAL_EXCHG' ELSE 'NEW' END AS FUNDING_SOURCE,
            CASE WHEN e.CONTRACT_TOTAL_FUND_VALUE_AMT = 0 THEN max(e.CONTRACT_TOTAL_FUND_VALUE_AMT) OVER (PARTITION BY AGREEMENT_CONTRACT_ID_NR) ELSE e.CONTRACT_TOTAL_FUND_VALUE_AMT END AS CONTRACT_TOTAL_FUND_VALUE_AMT
          FROM
            STDWDB.MIN.W_PFG_CS_HAL_PIT_CONTRACT_EXT e
            INNER JOIN STDWDB.MIN.W_PFG_CV_LIFE_INSURANCE_ARGT i ON e.ACT_PRODUCT_ARRANGEMENT_SK = i.ACT_PRODUCT_ARRANGEMENT_SK
            AND e.PRODUCT_SERVICE_LINE_OF_BUS_CD = 'ANN'
            AND PIT_VALUATION_DT >= '2018-12-31'
            AND i.CURRENT_RECORD_IND = 'Y'
            LEFT JOIN STDWDB.MIN.W_PFG_CV_LIF_APP_PREF_PRT_REQ app ON app.CONTRACT_ID_NR = i.AGREEMENT_CONTRACT_ID_NR
            AND app.PRINT_SEQUENCE_SEQ_NR = 1
            LEFT JOIN STDWDB.MIN.W_PFG_CV_LIFE_APP_AMD_INSU_RPL laair ON i.AGREEMENT_CONTRACT_ID_NR = laair.CONTRACT_ID_NR
            AND INSURANCE_REPLACE_SEQUENCE_NR = 1 --a contract can replace more than 1 older contract.  we don't care for this, we just need 1 record
            AND laair.CURRENT_RECORD_IND = 'Y'
        ) --END REGION
        UNION ALL
          (
            --REGION ALIP Section 4/19/19 onward
            SELECT
              substr(a.CONTRACT_ID, 2, 25) AS ARRANGEMENT_ID,
              a.CONTRACT_ID,
              p.ACT_PRODUCT_ARRANGEMENT_SK,
              p.CHN_PARTY_SK,
              p.ISSUE_DT,
              p.CVG_EFF_DT AS CONTRACT_EFFECTIVE_DT,
              walip.WORKER_PARTY_ID,
              issqual.DESCR_1_TXT AS TAX_QUALIFICATION_AC,
              a.AS_OF_DT AS PIT_VALUATION_DT,
              issfund.FUNDING_SOURCE,
              CASE WHEN a.PROD_SVCE_OFFER_AB = 'FGG' THEN a.CTRC_TOT_FUND_VALUE_AMT ELSE a.INITIAL_PREMIUM_AMT END AS CONTRACT_TOTAL_FUND_VALUE_AMT
            FROM
              STDWDB.MIN.W_LAH_CV_ALIP_POLICY p
              INNER JOIN STDWDB.MIN.W_LAH_CS_ALIP_PIT_CONTRACT a ON a.CONTRACT_ID = p.CONTRACT_NR
              AND a.AS_OF_DT >= '2018-12-31'
              AND p.VALID_TO_TS >= '2018-12-31'
              AND p.CURRENT_RECORD_IND = 'Y'
              LEFT JOIN STDWDB.MIN.W_LAH_CU_ALIP_TRANSLATION issqual ON p.QUALIFIED_IND = issqual.INPUT_1_KEY_ID
              AND issqual.GROUP_ID = 'Taxqualifier'
              AND issqual.INPUT_2_KEY_ID <> '!'
              LEFT JOIN (
                SELECT
                  DISTINCT issue.CONTRACT_NR,
                  CASE WHEN COUNT(DISTINCT trans.DESCR_1_TXT) OVER (PARTITION BY CONTRACT_NR) > 1 THEN 'Multiple' ELSE trans.DESCR_1_TXT END AS FUNDING_SOURCE
                FROM
                  (
                    SELECT
                      *,
                      ROW_NUMBER() OVER (
                        PARTITION BY CONTRACT_NR
                        ORDER BY
                          VALID_FROM_TS
                      ) AS ROWNUM
                    FROM
                      STDWDB.MIN.W_LAH_CV_ALIP_POLICY
                  ) issue
                  INNER JOIN STDWDB.MIN.W_LAH_CV_ALIP_SUSPENSE susp ON susp.CONTRACT_ID = issue.CONTRACT_NR
                  AND susp.TRANS_NR <> -999 --Invalid transactions
                  AND issue.ROWNUM = 1
                  LEFT JOIN STDWDB.MIN.W_LAH_CU_ALIP_TRANSLATION trans ON susp.CURR_SOURCE_TYPE_CD = trans.INPUT_1_KEY_ID
                  AND trans.GROUP_ID = 'TaxClass'
              ) issfund ON p.CONTRACT_NR = issfund.CONTRACT_NR
              LEFT JOIN STDWDB.MIN.W_PFG_WK_WORKER_PARTY_EXTRACT walip ON p.WORKER_PARTY_SK = walip.WORKER_PARTY_SK
            GROUP BY
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11
          ) --END REGION
        UNION ALL
          (
            --REGION ALIP Section 1/1/19 - 4/18/19
            SELECT
              substr(p.CONTRACT_NR, 2, 25) AS ARRANGEMENT_ID,
              p.CONTRACT_NR,
              p.ACT_PRODUCT_ARRANGEMENT_SK,
              p.CHN_PARTY_SK,
              p.ISSUE_DT,
              p.CVG_EFF_DT AS CONTRACT_EFFECTIVE_DT,
              walip.WORKER_PARTY_ID,
              issqual.DESCR_1_TXT AS TAX_QUALIFICATION_AC,
              d.WEEK_END_FRIDAY_DT AS PIT_VALUATION_DT,
              issfund.FUNDING_SOURCE,
              p.INITIAL_FACE_AMT AS CONTRACT_TOTAL_FUND_VALUE_AMT
            FROM
              STDWDB.MIN.W_LAH_CV_ALIP_POLICY p
              INNER JOIN (
                SELECT
                  CONTRACT_NR,
                  min(ISSUE_DT) AS miniss
                FROM
                  STDWDB.MIN.W_LAH_CV_ALIP_POLICY
                WHERE
                  year(ISSUE_DT) > 1900
                  AND VALID_TO_TS >= '2018-12-31'
                  AND VALID_FROM_TS <= '2019-04-18'
                GROUP BY
                  CONTRACT_NR
              ) miniss ON miniss.miniss = p.ISSUE_DT
              AND miniss.CONTRACT_NR = p.CONTRACT_NR
              INNER JOIN (
                SELECT
                  DISTINCT WEEK_END_FRIDAY_DT
                FROM
                  STDWDB.MIN.I_PFG_DM_DATE
                WHERE
                  WEEK_END_FRIDAY_DT BETWEEN '2018-12-27'
                  AND '2019-04-18'
              ) d ON d.WEEK_END_FRIDAY_DT >= p.ISSUE_DT
              AND year(p.ISSUE_DT) > 1900
              AND p.VALID_TO_TS >= '2018-12-31'
              AND P.VALID_FROM_TS <= '2019-04-18'
              INNER JOIN STDWDB.MIN.W_LAH_CU_ALIP_TRANSLATION issqual ON p.QUALIFIED_IND = issqual.INPUT_1_KEY_ID
              AND issqual.GROUP_ID = 'Taxqualifier'
              AND issqual.INPUT_2_KEY_ID <> '!'
              LEFT JOIN (
                SELECT
                  DISTINCT issue.CONTRACT_NR,
                  CASE WHEN COUNT(DISTINCT trans.DESCR_1_TXT) OVER (PARTITION BY CONTRACT_NR) > 1 THEN 'Multiple' ELSE trans.DESCR_1_TXT END AS FUNDING_SOURCE
                FROM
                  (
                    SELECT
                      *,
                      ROW_NUMBER() OVER (
                        PARTITION BY CONTRACT_NR
                        ORDER BY
                          VALID_FROM_TS
                      ) AS ROWNUM
                    FROM
                      STDWDB.MIN.W_LAH_CV_ALIP_POLICY
                  ) issue
                  INNER JOIN STDWDB.MIN.W_LAH_CV_ALIP_SUSPENSE susp ON susp.CONTRACT_ID = issue.CONTRACT_NR
                  AND susp.TRANS_NR <> -999 --Invalid transactions
                  AND issue.ROWNUM = 1
                  LEFT JOIN STDWDB.MIN.W_LAH_CU_ALIP_TRANSLATION trans ON susp.CURR_SOURCE_TYPE_CD = trans.INPUT_1_KEY_ID
                  AND trans.GROUP_ID = 'TaxClass'
              ) issfund ON p.CONTRACT_NR = issfund.CONTRACT_NR
              LEFT JOIN STDWDB.MIN.W_PFG_WK_WORKER_PARTY_EXTRACT walip ON p.WORKER_PARTY_SK = walip.WORKER_PARTY_SK
            GROUP BY
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11
          ) --END REGION
      ) halalip ON halalip.PIT_VALUATION_DT <= q1.PERIOD_END_DT + 61
      AND halalip.PIT_VALUATION_DT + 61 >= q1.PERIOD_END_DT
      AND halalip.ARRANGEMENT_ID = q1.ARRANGEMENT_ID
    WHERE
      q1.minUSAA_PARTY_SK = q1.CHN_PARTY_SK
  ) q2

**Comment by ajith1108** [comment]
@collerek can you please look into this?

**Comment by collerek** [comment]
Sure, i will take a look
