### ISSUE TITLE
Not supporting queries separated by ;

### ISSUE THREAD

**Issue by Selvi21** [macbre/sql-metadata#232]
Hi,
 I knew ";" marks the end of a query so the Parser ignores everything after it.But, it would be great if it parsers valid queries that comes after the ";" as well. This would help parsing multiple queries at the same time. The tool already supports multiple query parsing if the queries are not separated by ';'.

Current version :
Input : Parser (SELECT a.col1 FROM tbl1 a SELECT b.col2 FROM tbl2 b).columns
Output : [tbl1.col1 , tbl2.col2]

Input2: Parser (SELECT a.col1 FROM tbl1 a ; SELECT b.col2 FROM tbl2 b).columns
Output2 : [tbl1.col1 ]
The parser ignored the tbl2.col2 from input2. Since, the queries where separated by ';'.

**Comment by collerek** [comment]
That won't work properly if you pass i.e. select and update. 

There might be problems with resolving aliases and other unexpected results (like assigning column to query part etc.), not to mention same column names and/or aliases from different tables that would be mixed if not prefixed with tables.

You should simply split the query by `;` into a list of queries and parse them in a loop.

**Comment by Selvi21** [comment]
Agree with @collerek .
