### ISSUE TITLE
Parser not returning all columns when using "Distinct" keyword

### ISSUE THREAD

**Issue by cjlynch278** [macbre/sql-metadata#236]
When I'm using the distinct keyword, columns field will not include the column mentioned after the distinct keyword. For example:

parser = Parser("select distinct foo, bar, doink")
parser.columns --> ['bar','doink'] but I expect ['foo','bar','doink']

**Comment by collerek** [comment]
The current version supports it, please update the `sql-metadata` and try again.

```python
def test_issue_236():
    query = "select distinct foo, bar, doink"
    parser = Parser(query)
    assert parser.columns == ['foo', 'bar', 'doink']
```

**Comment by cjlynch278** [comment]
ah rats! missed the update. Thanks for the heads up.
