### ISSUE TITLE
Issue with table extraction for delete and drop query type

### ISSUE THREAD

**Issue by AviRaboah** [macbre/sql-metadata#260]
hi, 

Do you know why or when the above query type (delete, drop) should be supported? Or why it's not supported by now?

thanks.

**Comment by macbre** [comment]
@AviRaboah, can you provide SQL queries where this issue is present?

I'm getting the correct results form `DELETE` queries:

```python
>>> from sql_metadata import Parser
>>> Parser("DELETE FROM `foo`").query_type
<QueryType.DELETE: 'DELETE'>
>>> Parser("DELETE FROM `foo`").tables
['foo']
```

`DROP` queries are still not supprted:

```python
>>> Parser("DROP TABLE `foo`").tables
Not supported query type: DROP TABLE `foo`
```
