### ISSUE TITLE
v.2.3.0 'Parser' object has no attribute 'columns_without_subqueries'

### ISSUE THREAD

**Issue by Ben2277** [macbre/sql-metadata#280]
sql-metadata version: v.2.3.0

in my codes, when I run Parser.columns_without_subqueries, I found that is not work: 
```python
AttributeError: 'Parser' object has no attribute 'columns_without_subqueries'
```

but in parser.py file, the function `columns_without_subqueries(self) -> List:` is exist:
```python
    @property
    def columns_without_subqueries(self) -> List:
        """
        Returns columns without ones explicitly coming from sub-queries
        """
        columns = self.columns
        subqueries = self.subqueries_names
        return [column for column in columns if column.split(".")[0] not in subqueries]
```

**Comment by collerek** [comment]
You need to create an instance and pass the query first. Now you try to access the class attribute.
```python
parser = Parser(query)
print(parser.columns_without_subqueries)
```

**Comment by Ben2277** [comment]
> You need to create an instance and pass the query first. Now you try to access the class attribute.
> 
> ```python
> parser = Parser(query)
> print(parser.columns_without_subqueries)
> ```

sorry，I did not submit the complete code, in fact，I have used it as follows：
```python
from sql_metadata import Parser

sql = """
    /* !40100 comments */
    SELECT a.a, (a.b + a.c - a.u) as alias1, custome_func(b.d), '111' alias2 
      from aa as a left   join (select id, d from bb) b on a.id=b.id 
     where id in (select c.id from cc c where c.id < 100 and c.id2 in (1,2,3,4)) 
     order by alias1 limit 10,20;
    """

parser = Parser(sql)
print(parser.columns_without_subqueries)
```

and Traceback is:
```python
Traceback (most recent call last):
  File "/data/python_projects/joyee/dbquery/libs/test.py", line 13, in <module>
    a = parser.columns_without_subqueries
AttributeError: 'Parser' object has no attribute 'columns_without_subqueries'
```
I didn't find this problem in versions before 2.3.0.

thanks reply

**Comment by collerek** [comment]
Ahh, ok, sorry.

But when I check the source code of version 2.3 this property has been removed.

**Comment by Ben2277** [comment]
Oh，I checked the source code of version 2.3 again and indeed this property has been removed.

It's my mistake, thanks again.
