### ISSUE TITLE
Use Parser on a complete column containing SQL Statements.

### ISSUE THREAD

**Issue by HarryLeboeuf** [macbre/sql-metadata#322]
Hello,
I have a table in which one columns contains plenty of SQL statements (SQL Server Audit Log).
When trying to parse the tables used in those queries it goes a bit wild.
This is the statement
`parsed_col = '/'.join(sm.Parser(df["SqlStatement"]).tables)`

this is the error
`Traceback (most recent call last):
  File "d:\OneDrive\Documents\Sibelco\PowerBI\Synaps Monitoring\TestParse.py", line 12, in <module>
    parsed_col = '/'.join(sm.Parser(df["SqlStatement"]).tables)
  File "C:\Users\harry\AppData\Local\Programs\Python\Python39\lib\site-packages\sql_metadata\parser.py", line 37, in __init__
    self._query = self._preprocess_query()  File "C:\Users\harry\AppData\Local\Programs\Python\Python39\lib\site-packages\sql_metadata\parser.py", line 935, in _preprocess_query    if self._raw_query == "":
  File "C:\Users\harry\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py", line 1527, in __nonzero__     
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
PS C:\Users\harry>`

Any suggestions ?

**Comment by collerek** [comment]
You are passing a pandas Series while the parser accepts only strings as queries.

You have to iterate over your queries -> you can either dump values of a series to list and iterate or iterate on rows of pandas -> either way each time you have to pass one string to Parser.
