### ISSUE TITLE
Add support for ALTER TABLE ... APPEND

### ISSUE THREAD

**Issue by dargueta** [macbre/sql-metadata#33]
Can we add support for Redshift's [`ALTER TABLE ... APPEND`](https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE_APPEND.html) statement? I know it's a proprietary thing but it'd be nice.

Expected behavior:

```py
>>> sql_metadata.get_query_tables("ALTER TABLE x APPEND FROM y")                                                                                                                                                       
['x', 'y']
```

Currently `ALTER` is included in the returned set of tables.

**Comment by macbre** [comment]
Seems to be fixed by #40 - `sqlparse` update
