### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'value' when parsing a relatively simple inner query

### ISSUE THREAD

**Issue by dangoldin** [macbre/sql-metadata#377]
This feels as if it should work but failing. I'll try to look into it but thought I'd bring it up in case it's an easy fix.

```
SELECT max(dt) FROM
        (
         SELECT max(dt) as dt FROM t      
      UNION ALL
          SELECT max(dt) as dt FROM t2
        )
```

This query also fails so I wonder if it has to do with that specific query construction:

```
SELECT max(dt) FROM
        (
         SELECT max(dt) as dt FROM t      
        )
```

This is also failing
```
SELECT max(dt) FROM
        (
         SELECT dt  FROM t      
        )
```

**Comment by jiaohuix** [comment]
I have just found a solution where a SQL involving subqueries can have a semicolon at the end, for example:     


 `from sql_metadata.compat import get_query_tables,get_query_columns
query = '''
SELECT max(dt) FROM
        (
         SELECT max(dt) as dt FROM t      
      UNION ALL
          SELECT max(dt) as dt FROM t2
        );
'''
print(get_query_columns(query))
`

**Comment by dangoldin** [comment]
Oh nice - thanks for that!
