### ISSUE TITLE
LIKE operator pattern detected as column

### ISSUE THREAD

**Issue by ajugjacob** [macbre/sql-metadata#453]
Pattern to be searched when using `LIKE operator` is being detected as a columns.

Code to reproduce the result, using sql_metadata==2.10.0

```
from sql_metadata import Parser

sql_string = "select * from cars where description like %fast"
parser = Parser(sql_string)
print(parser.values)
```

This code gives the result `['*', 'description', 'fast']`

**Comment by macbre** [comment]
[MySQL requires the `LIKE` pattern to be provided as a string](https://dev.mysql.com/doc/refman/8.0/en/string-comparison-functions.html#operator_like) (hence, wrapped in quotes).
