### ISSUE TITLE
Support sqlparse 0.5.x

### ISSUE THREAD

**Issue by nimirium** [macbre/sql-metadata#482]
Hi, I noticed the latest `sql-metadata` (2.10.0) depends on `sqlparse >=0.4.1,<0.5.0`.
`sqlparse` has a [vulnerability](https://github.com/advisories/GHSA-2m57-hf25-phgg) that's fixed in v0.5.0.
I noticed that you fixed it in the code, could you please add a release that includes it?

**Comment by macbre** [comment]
The `sqlparse` has been updated by dependabot in #481. Sure, I'll tag and release the new version later today.

**Comment by macbre** [comment]
https://github.com/macbre/sql-metadata/releases/tag/v2.11.0
