### ISSUE TITLE
Incorrect column names when table aliases are used

### ISSUE THREAD

**Issue by akku1506** [macbre/sql-metadata#52]
sql_metadata.get_query_tables("SELECT a.* FROM users1 AS a JOIN users2 AS b ON a.ip_address = b.ip_address")

returns

users1, users2

While, 

**sql_metadata.get_query_columns("SELECT a.* FROM users1 AS a JOIN users2 AS b ON a.ip_address = b.ip_address")

returns

a.*, a.ip_address, b.ip_address**

Although, according to me, returning the below output makes more sense.

users1.*, users1.ip_address, users2.ip_adress

As, the aliases can be different for the query, while the table names and column names are still the same.

**Comment by macbre** [comment]
@akku1506, thanks for your report.

**Comment by iankotliar** [comment]
I've created a work around that solves this problem with some caveats.

```
# get table for alias. may fail if alias is used more than once in query
# won't get underlying columns for columns that are renamed
import sql_metadata
import re


def get_columns(query):
    columns = sql_metadata.get_query_columns(query)
    tables = sql_metadata.get_query_tables(query)
    aliases = list(set([x[0:x.find('.')] for x in columns if x.find('.') != -1]))
    alias_mapping = {}
    for alias in aliases:
        results = re.findall("((\w|\.)+)\s+"+"(as\s+)*"+alias+"((\s+)|,)", query)
        qc = 0

        for x in results:
            matched_table = ''
            if x[0] in tables:
                matched_table = x[0]
                qc += 1
        if qc == 1:
            alias_mapping[alias] = matched_table

    columns_with_tables = columns.copy()
    for i, x in enumerate(columns_with_tables):
        alias_index = x.find('.')
        if alias_index != -1 and alias_mapping.get(x[0:alias_index]) != None:
           columns_with_tables[i] =  alias_mapping.get(x[0:alias_index])+'.'+x[alias_index+1:]
    return columns_with_tables
```

**Comment by macbre** [comment]
@iankotliar, thanks for a workaround, but RegEx is clearly not the way to go. Given the fact that sql-metadata works on top of a tokenized SQL string.

**Comment by iankotliar** [comment]
Yeah, just a temporary workaround built on top of what you've already made. Thanks for working on this! It's very useful.
