### ISSUE TITLE
`get_query_tables` doesn't respect table names with dashes in their name

### ISSUE THREAD

**Issue by nickwu241** [macbre/sql-metadata#60]
To reproduce:
```python
import sql_metadata

sql_metadata.get_query_tables('SELECT * FROM "schema-with-dash"."tablename"')
['dash.tablename']
```

I expect this to return `schema-with-dash.tablename` or for them to be quoted.

**Comment by macbre** [comment]
@nickwu241 - dashes are not "legal" characters in names and need to be quoted properly:

```python
assert get_query_tables('SELECT * FROM `schema-with-dash.tablename`') == ['schema-with-dash.tablename']
```

gives the expected result. Hence, I'm going to close this ticket.
