### ISSUE TITLE
get_query_columns does not return nothing if parsing SELECT DISTINCT

### ISSUE THREAD

**Issue by benzzdan** [macbre/sql-metadata#72]
Hi, with the following query, I do not get any results:

>>> print(sql_metadata.get_query_columns("SELECT DISTINCT DATA.ASSAY_ID FROM foo"))
[]
>>> print(sql_metadata.get_query_columns("SELECT DATA.ASSAY_ID FROM foo"))
['DATA.ASSAY_ID']

Is this normal?

Regards

**Comment by macbre** [comment]
@benzzdan, nope. This looks like a bug :slightly_smiling_face:
