### ISSUE TITLE
Union's don't return the correct result

### ISSUE THREAD

**Issue by dylwylie** [macbre/sql-metadata#94]
Hey,

Thanks for the great library, I noticed that when a query has a "UNION ALL" statement an incorrect result can be returned

```
sql_metadata.get_query_tables("SELECT a,b,c FROM d UNION ALL SELECT e,f FROM g")
['d', 'f', 'g']
```

**Comment by macbre** [comment]
@dylwylie - this seems to work correctly on `sql_metadata` master branch - see #96 for a test case added.
